export const jobListings = [
  {
    id: 1,
    title: "Hackathon Organizer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full-time",
    category: "Event Management",
    experience: "3-5 years",
    salary: "$120,000 - $150,000",
    description:
      "Join Google's Developer Relations team to organize and manage internal and external hackathons. You'll be responsible for planning, coordinating, and executing hackathon events that drive innovation and community engagement.",
    requirements: [
      "Experience organizing tech events or hackathons",
      "Strong project management skills",
      "Excellent communication and interpersonal abilities",
      "Technical background preferred but not required",
      "Passion for developer communities and innovation",
    ],
    responsibilities: [
      "Plan and execute hackathon events from concept to completion",
      "Coordinate with cross-functional teams including engineering, marketing, and facilities",
      "Manage hackathon budgets and resources",
      "Develop hackathon themes, challenges, and judging criteria",
      "Build relationships with sponsors, partners, and participants",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Comprehensive health benefits",
      "Free meals and snacks",
      "Generous vacation policy",
      "Professional development budget",
    ],
    postedDate: "2023-11-10",
    applicationDeadline: "2023-12-10",
    logo: "/google-logo.png",
    featured: true,
  },
  {
    id: 2,
    title: "Full Stack Developer",
    company: "Microsoft",
    location: "Redmond, WA",
    type: "Full-time",
    category: "Engineering",
    experience: "2-4 years",
    salary: "$110,000 - $140,000",
    description:
      "Join Microsoft's developer tools team to build and enhance platforms that support hackathons and innovation events. You'll work on full-stack applications that help organize, run, and showcase hackathon projects.",
    requirements: [
      "Experience with React, Node.js, and modern JavaScript frameworks",
      "Familiarity with cloud services (Azure preferred)",
      "Strong problem-solving skills",
      "Experience with database design and management",
      "Collaborative mindset and team player attitude",
    ],
    responsibilities: [
      "Develop and maintain web applications for hackathon management",
      "Implement features for project submission, judging, and showcasing",
      "Optimize application performance and scalability",
      "Collaborate with UX designers to create intuitive interfaces",
      "Participate in code reviews and maintain high code quality",
    ],
    benefits: [
      "Competitive salary and stock options",
      "Comprehensive health and wellness benefits",
      "401(k) matching",
      "Professional development opportunities",
      "Flexible work arrangements",
    ],
    postedDate: "2023-11-05",
    applicationDeadline: "2023-12-05",
    logo: "/microsoft-logo.png",
    featured: true,
  },
  {
    id: 3,
    title: "Innovation Program Manager",
    company: "Amazon",
    location: "Seattle, WA",
    type: "Full-time",
    category: "Program Management",
    experience: "4-6 years",
    salary: "$130,000 - $160,000",
    description:
      "Amazon is seeking an Innovation Program Manager to lead our internal hackathon and innovation initiatives. You'll be responsible for designing and implementing programs that foster creativity and drive product innovation across the organization.",
    requirements: [
      "Experience managing innovation programs or hackathons",
      "Strong leadership and organizational skills",
      "Excellent communication and presentation abilities",
      "Data-driven approach to measuring program success",
      "Ability to work with diverse teams across multiple departments",
    ],
    responsibilities: [
      "Design and implement innovation programs including hackathons",
      "Create frameworks for evaluating and advancing promising ideas",
      "Collaborate with leadership to align innovation initiatives with company goals",
      "Mentor teams and individuals on innovation methodologies",
      "Track and report on program metrics and outcomes",
    ],
    benefits: [
      "Competitive compensation package",
      "Comprehensive benefits including health, dental, and vision",
      "401(k) with company match",
      "Restricted stock units (RSUs)",
      "Paid time off and parental leave",
    ],
    postedDate: "2023-10-28",
    applicationDeadline: "2023-11-28",
    logo: "/amazon-logo.png",
    featured: false,
  },
  {
    id: 4,
    title: "Developer Advocate",
    company: "Meta",
    location: "Menlo Park, CA",
    type: "Full-time",
    category: "Developer Relations",
    experience: "3-5 years",
    salary: "$125,000 - $155,000",
    description:
      "Join Meta as a Developer Advocate to support our hackathon community. You'll help developers build innovative solutions using Meta's technologies and platforms, while organizing and supporting hackathon events.",
    requirements: [
      "Technical background with hands-on development experience",
      "Experience with Meta's developer platforms (React, GraphQL, etc.)",
      "Strong public speaking and presentation skills",
      "Content creation abilities (blogs, tutorials, videos)",
      "Community building experience",
    ],
    responsibilities: [
      "Organize and support hackathons featuring Meta technologies",
      "Create technical content to help developers succeed",
      "Speak at events and represent Meta in the developer community",
      "Gather feedback from developers to improve Meta's platforms",
      "Mentor developers building on Meta technologies",
    ],
    benefits: [
      "Competitive salary and equity",
      "Comprehensive health benefits",
      "Wellness stipend",
      "Professional development budget",
      "30 days of paid time off",
    ],
    postedDate: "2023-10-20",
    applicationDeadline: "2023-11-20",
    logo: "/meta-logo-abstract.png",
    featured: false,
  },
  {
    id: 5,
    title: "Technical Event Coordinator",
    company: "Spotify",
    location: "New York, NY",
    type: "Full-time",
    category: "Event Management",
    experience: "2-4 years",
    salary: "$85,000 - $110,000",
    description:
      "Spotify is looking for a Technical Event Coordinator to help organize our Hack Week and other technical events. You'll work with engineering teams to create engaging and productive hackathon experiences that drive innovation.",
    requirements: [
      "Experience coordinating technical events or hackathons",
      "Strong organizational and multitasking abilities",
      "Excellent communication skills",
      "Basic technical understanding of software development",
      "Creative problem-solving approach",
    ],
    responsibilities: [
      "Coordinate all aspects of Spotify's Hack Week events",
      "Manage event logistics, scheduling, and resources",
      "Develop engaging activities and challenges for participants",
      "Coordinate judging and prizes for hackathon projects",
      "Document and share outcomes from innovation events",
    ],
    benefits: [
      "Competitive salary",
      "Generous health, dental, and vision coverage",
      "Flexible work arrangements",
      "Parental leave",
      "Learning and development opportunities",
    ],
    postedDate: "2023-10-15",
    applicationDeadline: "2023-11-15",
    logo: "/spotify-logo.png",
    featured: false,
  },
  {
    id: 6,
    title: "Innovation Lab Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    type: "Full-time",
    category: "Engineering",
    experience: "3-6 years",
    salary: "$140,000 - $180,000",
    description:
      "Join Netflix's Innovation Lab to support our Hack Day events and develop experimental projects. You'll work on cutting-edge technologies and help create a culture of innovation within the company.",
    requirements: [
      "Strong software engineering background",
      "Experience with rapid prototyping and MVPs",
      "Familiarity with a wide range of technologies and frameworks",
      "Creative thinking and problem-solving abilities",
      "Collaborative mindset",
    ],
    responsibilities: [
      "Support Netflix's Hack Day events with technical resources and guidance",
      "Develop and maintain tools for hackathon project development",
      "Create proof-of-concept projects to explore new technologies",
      "Mentor other engineers during innovation events",
      "Help evaluate and advance promising hackathon projects",
    ],
    benefits: [
      "Top-of-market salary",
      "Netflix stock options",
      "Comprehensive health benefits",
      "Unlimited vacation policy",
      "Professional development opportunities",
    ],
    postedDate: "2023-10-10",
    applicationDeadline: "2023-11-10",
    logo: "/netflix-logo.png",
    featured: false,
  },
  {
    id: 7,
    title: "Hackathon Community Manager",
    company: "Airbnb",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Community",
    experience: "2-4 years",
    salary: "$95,000 - $120,000",
    description:
      "Airbnb is seeking a Hackathon Community Manager to build and nurture our internal innovation community. You'll organize quarterly hackathons and create programs that encourage creativity and problem-solving across the organization.",
    requirements: [
      "Experience managing communities or organizing events",
      "Strong communication and relationship-building skills",
      "Project management abilities",
      "Understanding of technical concepts and software development",
      "Passion for innovation and creative problem-solving",
    ],
    responsibilities: [
      "Organize and manage Airbnb's quarterly hackathons",
      "Build and nurture a community of innovators within the company",
      "Create content and resources to support hackathon participants",
      "Develop programs to recognize and reward innovation",
      "Track and report on community engagement and hackathon outcomes",
    ],
    benefits: [
      "Competitive salary and equity",
      "Comprehensive health benefits",
      "Travel credits",
      "Paid volunteer time",
      "Learning and development budget",
    ],
    postedDate: "2023-10-05",
    applicationDeadline: "2023-11-05",
    logo: "/generic-travel-logo.png",
    featured: false,
  },
  {
    id: 8,
    title: "Technical Program Manager - Hackathons",
    company: "IBM",
    location: "Remote",
    type: "Full-time",
    category: "Program Management",
    experience: "4-7 years",
    salary: "$115,000 - $145,000",
    description:
      "IBM is looking for a Technical Program Manager to lead our Call for Code hackathon initiative. You'll be responsible for organizing global hackathons focused on using technology to address humanitarian challenges.",
    requirements: [
      "Experience managing technical programs or events",
      "Strong project management skills",
      "Global perspective and cultural awareness",
      "Understanding of humanitarian challenges and social impact",
      "Ability to work with diverse stakeholders",
    ],
    responsibilities: [
      "Lead the planning and execution of global Call for Code hackathons",
      "Coordinate with partners including the UN and Linux Foundation",
      "Develop hackathon challenges aligned with humanitarian needs",
      "Manage program budgets and resources",
      "Measure and report on program impact",
    ],
    benefits: [
      "Competitive salary",
      "Comprehensive benefits package",
      "401(k) matching",
      "Professional development opportunities",
      "Flexible work arrangements",
    ],
    postedDate: "2023-09-28",
    applicationDeadline: "2023-10-28",
    logo: "/ibm-logo.png",
    featured: false,
  },
  {
    id: 9,
    title: "Innovation Coach",
    company: "Salesforce",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Training & Development",
    experience: "5-8 years",
    salary: "$130,000 - $160,000",
    description:
      "Salesforce is seeking an Innovation Coach to support our hackathon and innovation programs. You'll train and mentor employees on innovation methodologies and help teams develop and advance their hackathon projects.",
    requirements: [
      "Experience with innovation methodologies (Design Thinking, Lean Startup, etc.)",
      "Strong coaching and mentoring skills",
      "Background in product development or engineering",
      "Excellent facilitation and presentation abilities",
      "Track record of driving innovation in organizations",
    ],
    responsibilities: [
      "Design and deliver innovation training programs",
      "Coach teams during hackathons and innovation events",
      "Develop frameworks and tools for effective innovation",
      "Help teams refine and advance promising hackathon projects",
      "Build a culture of innovation across the organization",
    ],
    benefits: [
      "Competitive salary and equity",
      "Comprehensive health benefits",
      "401(k) matching",
      "Educational reimbursement",
      "Volunteer time off",
    ],
    postedDate: "2023-09-20",
    applicationDeadline: "2023-10-20",
    logo: "/salesforce-logo.png",
    featured: false,
  },
  {
    id: 10,
    title: "Hackathon Platform Developer",
    company: "HackNHost",
    location: "Remote",
    type: "Full-time",
    category: "Engineering",
    experience: "2-5 years",
    salary: "$100,000 - $130,000",
    description:
      "Join HackNHost to build the next generation of hackathon management platforms. You'll develop features that help organizations run successful hackathons, from registration and team formation to project submission and judging.",
    requirements: [
      "Strong full-stack development skills",
      "Experience with React, Node.js, and modern web technologies",
      "Understanding of hackathon processes and needs",
      "Database design and management experience",
      "Passion for supporting innovation communities",
    ],
    responsibilities: [
      "Develop and maintain the HackNHost platform",
      "Implement features for hackathon management",
      "Optimize platform performance and scalability",
      "Collaborate with UX designers to create intuitive interfaces",
      "Gather and incorporate user feedback",
    ],
    benefits: [
      "Competitive salary and equity",
      "Remote-first culture",
      "Flexible working hours",
      "Health insurance stipend",
      "Professional development budget",
    ],
    postedDate: "2023-09-15",
    applicationDeadline: "2023-10-15",
    logo: "/tech-startup-logo.png",
    featured: true,
  },
]
